/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Teste.de.software;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static io.restassured.RestAssured.when;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

public class AppTest {

    //roda apenas uma vez
    @BeforeClass
    public static void setup() {
        //Usar o .log().all() faz o programa ser mais verboso no erro.
        //Esse comando subistituiu todos meus .log().all()
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test
    public void testeListaMetaDadosDoUsuario() {
        //Escrita do restAssured para testar a api do site https://reqres.in
        when().
                get("https://reqres.in/api/users?page=2").
        then().
                //is() é do hamcrest, eu não coloquei a dependência dele no build.gradle
                //Portanto, ele puxou do JUNIT ou do restAssured
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }

    @Test
    public void testeCriaUsuarioComSucesso() {

        given().//.log().all().
                //Tenho que informar que estou passando um JSON
                contentType(ContentType.JSON).
                //Copiado do Postman
                body("{\"name\": \"Diego\", \"job\": \"Jogador\"}").
        when().
            post("https://reqres.in/api/users").
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", is("Diego"));
    }
}